import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFileSync } from 'node:fs';
import { NextRequest } from 'next/server';
import { correctText } from '../lib/editor/correct';
import { restoreWord } from '../lib/editor/lexicon';
import { getStrategyRegistry } from '../lib/strategies/bootstrap';
import { POST } from '../app/api/transform/route';

const { input } = JSON.parse(readFileSync(new URL('./fixtures/platform-proposal.json', import.meta.url), 'utf8'));

// Independently reviewed language targets, including phrase meaning, punctuation
// and unchanged English terminology, rather than a snapshot generated by the engine.
const reviewed = [
  'Hörmətli tərəfdaşımız,\n\nŞirkətimizin',
  'biznes tələbləri mütəxəssislərimiz tərəfindən',
  'nəzərdən keçirilmişdir. Müəyyən olunmuş hədəflər',
  'icra mərhələləri, funksional modulların strukturu, texniki xarakteristikalar',
  'rəqəmsal mühitə köçürülməsi', 'iki həftəlik müddəti',
  'siyahısındakı tapşırıqlar', 'platformanın gedişatını real vaxtda qiymətləndirməyə',
  'İstifadəçi idarəetməsi, ödəniş inteqrasiyaları, bildiriş servisləri',
  'Kubernetes vasitəsilə', 'gRPC protokolu', 'relational, həm də NoSQL',
  'transactional əməliyyatlar', 'PostgreSQL', 'Redis keşləmə',
  'REST və OpenAPI standartlarından', 'API keys və OAuth2',
  'aktiv olacaq. RabbitMQ və ya Kafka', 'retry mexanizmləri',
  'UX/UI', 'responsive dizayn', 'dynamic filtrləmə', 'TLS və SSL',
  'mənfəət məlumatları hashing', 'RBAC', '2FA', 'CI/CD',
  'unit testlər, inteqrasiya testləri və e2e testlərdən',
  'proqram koduna', 'mühitə düşməsinin qarşısını',
  'zero downtime deployment', 'roll-back', 'Prometheus və Grafana',
  'dörd həftə ərzində', 'on iki həftəlik', 'yüz faiz',
];

test('the app strategy meets reviewed proposal corrections and preserves its commitments', async () => {
  const result = await getStrategyRegistry().get('text-corrector').transform({ text: input });
  for (const expected of reviewed) assert.ok(result.transformedText.includes(expected), expected);
  assert.doesNotMatch(result.transformedText, /öpən API|hefdelik|muvite|kecirileceyidir/u);
  assert.equal(result.metadata.engine, 'local-rules');
  assert.equal(correctText(result.transformedText).text, result.transformedText);
  assert.equal(correctText(input, true).text.split('\n').length, input.split('\n').length);
});

test('HTTP and app strategy produce exactly the same full proposal without external calls', async () => {
  const oldFetch = globalThis.fetch;
  globalThis.fetch = async () => { throw new Error('Unexpected external call'); };
  try {
    const response = await POST(new NextRequest('http://localhost/api/transform', {
      method: 'POST', headers: { 'content-type': 'application/json', 'x-forwarded-for': '192.0.2.71' },
      body: JSON.stringify({ strategyId: 'text-corrector', text: input }),
    }));
    assert.equal(response.status, 200);
    assert.equal((await response.json()).transformedText, correctText(input).text);
  } finally { globalThis.fetch = oldFetch; }
});

test('English vocabulary stays English and inherited object keys cannot become replacements', () => {
  for (const word of ['backend', 'frontend', 'framework', 'startup', 'database',
    'deploy', 'commit', 'open', 'responsive', 'dynamic', 'hashing', 'transactional',
    'retry', 'roll-back', 'constructor', 'toString']) {
    assert.equal(restoreWord(word), word, word);
  }
  assert.equal(restoreWord('öpən'), 'öpən');
  assert.equal(correctText('rest ve open api standartlari').text, 'REST və OpenAPI standartları.');
});

test('new sentence rules apply to short unseen messages without splitting subordinate clauses', () => {
  assert.equal(correctText('novbeler aktiv olacaq rabbitmq isleyir').text,
    'Növbələr aktiv olacaq. RabbitMQ işləyir.');
  assert.equal(correctText('dord hefde sonra testler baslayacaq').text,
    'Dörd həftə sonra testlər başlayacaq.');
  assert.equal(correctText('Mən bilirəm ki, sistem hazırdır.').text,
    'Mən bilirəm ki, sistem hazırdır.');
});

test('technical phrase normalization does not touch code, URL paths or identifiers', () => {
  const code = '```txt\nopen api no sql ci cd ux ui oauth2 2fa\n```';
  assert.equal(correctText(code).text, code);
  for (const value of ['https://example.com/open?x=api', '`open api`', 'api_keys', 'oauth2_client']) {
    assert.ok(correctText(value).text.includes(value), value);
  }
});
