/** Frozen review sentences; no output or expectation is learned from correctText. */
import { writeFileSync } from 'node:fs';
import { correctText } from '../lib/editor/correct';
const originals = [
  'Bu səhər dəniz sakit idi.', 'Dünən gecə şəhərdə yağış yağdı.',
  'Dostlarım köhnə məktəbin qarşısında görüşdülər.', 'Yaşıl ağacların altında uşaqlar oynayırdı.',
  'Nənəm mənə maraqlı bir hekayə danışdı.', 'Kitabxanada nadir əlyazmalar saxlanılır.',
  'Pəncərədən soyuq külək içəri doldu.', 'Qatar səhər saatlarında stansiyaya çatdı.',
  'Sürücü dar küçədə maşını saxladı.', 'Tələbələr dərsdən sonra parkda gəzdilər.',
  'Məktəbin həyətində yeni ağaclar əkildi.', 'Rəssam sərgidə üç rəsm təqdim etdi.',
  'Bu gün hava xeyli sərin idi.', 'Axşam işıqlar bir-bir yandı.',
  'Səhər yeməyindən sonra gəzintiyə çıxdıq.', 'O, dostuna uzun bir məktub yazdı.',
  'Uşaqlar kitab oxumağı çox sevirlər.', 'Sahil boyunca sakitcə addımladıq.',
  'İclas vaxtında başa çatdı.', 'Müəllim mövzunu aydın izah etdi.',
  'Yeni server bu gün quraşdırıldı.', 'API sorğuları sürətlə cavablandırılır.',
  'Komanda layihənin kodunu yoxladı.', 'Backend xidməti artıq işləyir.',
  'Frontend səhifəsi mobil cihazlarda açılır.', 'Git tarixçəsində yeni commit görünür.',
  'Database serverinə giriş məhdudlaşdırıldı.', 'Deploy mərhələsi uğurla başa çatdı.',
  'Sistem jurnalında köhnə xətalar qaldı.', 'Şəbəkə kəsildikdə proses dayandı.',
  'Proqram istifadəçiyə aydın xəta göstərdi.', 'Test mühitində fərqli nəticə alındı.',
  'Kodun keyfiyyəti mütəmadi yoxlanılır.', 'Serverin yaddaşı axşam doldu.',
  'Sənədin son versiyası saxlanıldı.', 'Məlumat bazası gündəlik yenilənir.',
  'Faylın ölçüsü kifayət qədər böyükdür.', 'Axtarış sistemi cavabı tez qaytardı.',
  'Yeni modul dünən təqdim edildi.', 'Texniki qrup problemi araşdırdı.',
  'Teleskop uzaq qalaktikaları müşahidə edir.', 'Kainatda saysız-hesabsız ulduz var.',
  'Günəş işığı Yerə enerji verir.', 'Planetlərin hərəkəti diqqətlə izlənilir.',
  'Alimlər yeni dərman üzərində işləyirlər.', 'Laboratoriyada aparılan sınaq tamamlandı.',
  'Meşələr təbiətin tarazlığını qoruyur.', 'Çayların suyu yazda artır.',
  'Dənizin dərinliyində müxtəlif canlılar yaşayır.', 'Buludlar yavaş-yavaş dağıldı.',
  'Fiziki məşqlər sağlamlığa kömək edir.', 'Müntəzəm yuxu zehni fəaliyyəti yaxşılaşdırır.',
  'Təmiz hava uşaqlara faydalıdır.', 'Torpağın tərkibi laboratoriyada ölçüldü.',
  'Şagirdlər müşahidə nəticələrini yazdılar.', 'Müəllim təcrübəni təhlükəsiz apardı.',
  'Təbiətşünaslar yeni bitki növü tapdılar.', 'Qaranlıq səma ulduzları daha aydın göstərir.',
  'Dünənki külək ağacları yellətdi.', 'Araşdırmanın nəticələri jurnalda çap olundu.',
  'Müştəri yeni təklifi nəzərdən keçirdi.', 'Müqavilənin şərtləri bu gün təsdiqləndi.',
  'Rəhbərlik layihəyə əlavə vaxt ayırdı.', 'Təlim proqramı gələn həftə başlayacaq.',
  'Komanda yekun hesabatı vaxtında göndərdi.', 'Ödənişin tarixi müqavilədə göstərilib.',
  'Yeni işçilər bu gün ofisə gəldilər.', 'Görüş üçün ayrıca otaq ayrıldı.',
  'Sənədlərin surəti elektron qaydada göndərildi.', 'Sorğu müvafiq şöbəyə yönləndirildi.',
  'Müştəri xidməti hər gün fəaliyyət göstərir.', 'Layihənin büdcəsi yenidən hesablandı.',
  'İşçilər təhlükəsizlik qaydalarını öyrəndilər.', 'Yeni filial payızda açılacaq.',
  'Hesabatda əsas nəticələr qeyd edildi.', 'Təklifin detalları sabah müzakirə olunacaq.',
  'Ekspertlər texniki tələbləri yoxladılar.', 'Şirkət uzunmüddətli tərəfdaşlıq istəyir.',
  'İdarə heyəti layihəni təsdiqlədi.', 'Hər şöbə öz planını hazırladı.',
  'Bakı bu gün çox sakit görünürdü.', 'Gəncədən gələn dostumla görüşdüm.',
  'Şuşa barədə yeni kitab oxudum.', 'Qəbələyə səhər tezdən yola düşdük.',
  'Sumqayıtdan axşam qayıtdılar.', 'Naxçıvanın tarixi çox qədimdir.',
  'Azərbaycanın müxtəlif bölgələri var.', 'Laçında hava bu gün sərin idi.',
  'Türkiyəyə səfər planlaşdırıldı.', 'Qubanın meşələri yazda gözəldir.',
  'Əli müəllim sinfə daxil oldu.', 'Fidan xanım hesabatı təqdim etdi.',
  'Rəşad Əliyev tədbirə qatıldı.', 'Mən ümid edirəm ki, hər şey yaxşı olacaq.',
  'Bağda fidan əkmək faydalıdır.', 'Bu mənə ilham verdi.',
  'Sadiq dost həmişə kömək edir.', 'Dəniz bu səhər sakitdir.',
  'Müzakirə sona çatdı.', 'Lalə bağda açdı.',
  'Səhər müəllim yeni mövzunu izah etdi.', 'Kəndin yaxınlığında köhnə körpü var.',
  'Balaca it qapının önündə oturdu.', 'Payızda bağdakı yarpaqlar saralır.',
  'Otaqda böyük bir xəritə asılıb.', 'Təyyarə günortadan sonra hava limanına endi.',
  'Qonşular həyətdə birlikdə işlədilər.', 'Dostum mənə yeni kitab hədiyyə etdi.',
  'İmtahan nəticələri sabah açıqlanacaq.', 'Hər kəs öz növbəsini sakitcə gözlədi.',
  'Qış axşamları kənd daha sakit olur.', 'Dünənki tamaşa hamının xoşuna gəldi.',
  'Uşaq bağçada rəngli şəkillər çəkdi.', 'Köhnə fotoşəkillərə baxıb xatirələri yada saldıq.',
  'İdmançılar yarışdan əvvəl isinmə hərəkətləri etdilər.', 'Dəniz sahilində kiçik bir mayak var.',
  'Səhər bazarında təzə tərəvəz satılırdı.', 'Musiqiçilər konsertə uzun müddət hazırlaşdılar.',
  'Brauzer yeni səhifəni problemsiz açdı.', 'Router bir neçə cihazı şəbəkəyə qoşdu.',
  'Terminalda yeni qovluq yaratdım.', 'İstifadəçi səhifəni yenidən yüklədi.',
  'Məlumatların ehtiyat nüsxəsi gecə hazırlandı.', 'Sistem eyni sorğunu iki dəfə emal etdi.',
  'Dizayner düymənin yerini dəyişdi.', 'İnkişaf komandası xəta hesabatını oxudu.',
  'Alqoritm böyük siyahını sürətlə çeşidlədi.', 'Yeni versiya əvvəlki məlumatları saxladı.',
  'Kod redaktoru faylı avtomatik formatladı.', 'İnterfeysdəki yazılar aydın görünür.',
  'Mühəndis serverin temperaturunu ölçdü.', 'Yeni funksiya gözlənilən nəticəni verdi.',
  'Qurğunun batareyası gün ərzində boşaldı.', 'Məlumatlar təhlükəsiz şəkildə ötürüldü.',
  'Fayl yüklənərkən bağlantı kəsildi.', 'İstifadəçinin seçimi yadda saxlanıldı.',
  'Komanda səhvləri birlikdə təhlil etdi.', 'Sistem xətadan sonra yenidən işə düşdü.',
  'Külək turbinləri elektrik enerjisi istehsal edir.', 'Şəhərin kənarında yeni park salındı.',
  'Buzlaqların əriməsi su səviyyəsini dəyişir.', 'Qaranquşlar yazda geri qayıdırlar.',
  'Gecə səmasında parlaq ulduz göründü.', 'Tədqiqatçılar quşların köçünü izlədilər.',
  'Yağışdan sonra torpaq nəm idi.', 'Dərənin içindən sərin çay axır.',
  'Alim köhnə qeydləri yenidən araşdırdı.', 'Gölün sahilində müxtəlif bitkilər bitir.',
  'Yer kürəsi Günəş ətrafında fırlanır.', 'Mikroskop altında hüceyrələr müşahidə olundu.',
  'İqlim göstəriciləri hər il yenilənir.', 'Təmiz içməli su hər kəs üçün vacibdir.',
  'Dağlarda hava tez-tez dəyişir.', 'Şagird suyun temperaturunu qeyd etdi.',
  'Dərmanlar həkimin göstərişi ilə qəbul olunur.', 'Bəzi heyvanlar qışda yuxuya gedir.',
  'Bitkinin böyüməsi üçün kifayət qədər işıq lazımdır.', 'Təcrübənin nəticəsi müəllimi təəccübləndirdi.',
  'İş görüşü səhər saatlarında keçirildi.', 'Müştərinin sualına yazılı cavab göndərildi.',
  'Əməkdaşlar yeni qaydalarla tanış oldular.', 'Sifarişin çatdırılma tarixi dəqiqləşdirildi.',
  'Menecer bütün hesabatları bir yerə topladı.', 'Tərəfdaşlar gələcək layihələri müzakirə etdilər.',
  'Təlimdə iştirak edənlərə sənəd verildi.', 'Yeni təklif rəsmi məktubla çatdırıldı.',
  'Xidmət haqqı hər ay hesablanır.', 'Şöbə müdiri iş qrafikini paylaşdı.',
  'Tədbirdə bir neçə xarici qonaq iştirak etdi.', 'Sənədin əlavələri ayrıca göndərildi.',
  'Maliyyə planı növbəti rübdə yenilənəcək.', 'İşçilərin təklifləri diqqətlə dinlənildi.',
  'Sorğunun cavabı qeydiyyat nömrəsi ilə saxlanıldı.', 'Rəhbər yeni tapşırıqları bölüşdürdü.',
  'İllik nəticələr ümumi iclasda təqdim edildi.', 'Müştəri müqaviləni diqqətlə oxudu.',
  'Layihənin əsas mərhələsi vaxtında tamamlandı.', 'Şirkətin yeni ofisi şəhərin mərkəzindədir.',
  'Quba rayonunda çoxlu meyvə bağları var.', 'Şəkidə qədim küçələr qorunub saxlanılır.',
  'Gəncəyə gələn qonaqlar muzeyi ziyarət etdilər.', 'Şamaxının təbiəti yazda dəyişir.',
  'Bərdədən gələn məktub bu gün çatdı.', 'Astara yaxınlığında dəniz görünür.',
  'Naxçıvana qışda səfər etmişdim.', 'Qarabağ bölgəsinin tarixi araşdırılır.',
  'Azərbaycan Dəmir Yolları yeni cədvəl açıqladı.', 'Bakı Dövlət Universiteti tədbir təşkil etdi.',
  'Əli Əliyev müəllimlə söhbət etdi.', 'Vəli bəy iclasda söz aldı.',
  'Aysel xanım yeni sənədi imzaladı.', 'Fidan bağda suvarma işinə kömək etdi.',
  'İlham mənbəyi gündəlik müşahidələrdir.', 'Sona adlı tələbə yarışda qalib gəldi.',
  'Dəniz sahilində axşam külək əsdi.', 'Ümid bəy sabah yola çıxacaq.',
  'Gül bağda yeni çiçəklər əkdi.', 'Sadiq insan sözünə əməl edir.',
  'Səhər avtobusu dayanacağa vaxtında çatdı.', 'Yeni muzeyin qapıları ziyarətçilərə açıldı.',
] as const;
if (originals.length !== 200) throw new Error(`Expected 200 distinct source sentences, found ${originals.length}`);
const ascii = (s: string) => s.toLocaleLowerCase('az-AZ').replace(/[əıçğöşü]/gu,
  c => ({ ə: 'e', ı: 'i', ç: 'c', ğ: 'g', ö: 'o', ş: 's', ü: 'u' })[c] ?? c);
const cases = originals.flatMap((expected, index) => [
  { id: `unseen-ascii-${index + 1}`, category: 'undiacritized', input: ascii(expected).replace(/[.!?]$/u, ''), expected },
  { id: `unseen-punctuation-${index + 1}`, category: 'punctuation-capitalization',
    input: expected.toLocaleLowerCase('az-AZ').replace(/[.!?]$/u, ''), expected },
]);
const results = cases.map(item => {
  const actual = correctText(item.input).text;
  return { ...item, actual, passed: actual === item.expected,
    idempotent: correctText(actual).text === actual };
});
const passed = results.filter(item => item.passed).length;
const report = { total: results.length, distinctMeanings: originals.length, passed,
  failed: results.length - passed, results };
writeFileSync(new URL('../docs/unseen-evaluation-results.json', import.meta.url), JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify({ total: report.total, distinctMeanings: report.distinctMeanings, passed, failed: report.failed,
  failures: results.filter(item => !item.passed).slice(0, 25) }, null, 2));
if (report.failed !== 0 || results.some(item => !item.idempotent)) {
  process.exitCode = 1;
}
